language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install -y libevent-dev python-gevent
install:
    - python setup.py develop
script: make test
notifications:
    email:
        - tarek@mozilla.com
        - alexis@mozilla.com
    irc: "irc.mozilla.org#services-dev"
    on_success: change
