language: python
python:
    - "2.7"
install:
    - python setup.py develop
script: make test
notifications:
    email: tarek@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
